// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnx8LL6mYHKYn9jwisKHAMHifCYnf6PQ',
    appId: '1:916264511856:web:edaa4491a8ecfa796e07b5',
    messagingSenderId: '916264511856',
    projectId: 'fir-e8459',
    authDomain: 'fir-e8459.firebaseapp.com',
    storageBucket: 'fir-e8459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3fB0Ggpxt4Z3ffrIyUASL9mIMNb4YFY',
    appId: '1:916264511856:android:d1fd65448386915c6e07b5',
    messagingSenderId: '916264511856',
    projectId: 'fir-e8459',
    storageBucket: 'fir-e8459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hGpzK3IOGQnY6mXVp1YDcnYq8zEloRI',
    appId: '1:916264511856:ios:9f594e712c4bb4696e07b5',
    messagingSenderId: '916264511856',
    projectId: 'fir-e8459',
    storageBucket: 'fir-e8459.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hGpzK3IOGQnY6mXVp1YDcnYq8zEloRI',
    appId: '1:916264511856:ios:3ea533449dd0dd316e07b5',
    messagingSenderId: '916264511856',
    projectId: 'fir-e8459',
    storageBucket: 'fir-e8459.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
